# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.9. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class HelloWorld < Formula
  desc ""
  homepage "https://github.com/muquit/hello-world"
  version "1.0.6"
  license "MIT"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/hello-world/releases/download/v1.0.6/hello-world-v1.0.6-darwin-arm64.d.tar.gz"
    sha256 "7ee49e76bd48fd579f1f5a4375b712cc95fd3ca80dcc98619aa72b69db08d3df"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/hello-world/releases/download/v1.0.6/hello-world-v1.0.6-darwin-amd64.d.tar.gz"
    sha256 "2b8b39af42546f3373fd41df4d35ac955f7a57471f31a95c526a1580633be9cc"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/hello-world/releases/download/v1.0.6/hello-world-v1.0.6-linux-amd64.d.tar.gz"
    sha256 "5c6fa56a34ce5dbe6bb2080222c2ace8e564cc642a473389749fcff8aa05bf78"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/hello-world/releases/download/v1.0.6/hello-world-v1.0.6-linux-arm64.d.tar.gz"
    sha256 "1c8ec50c52372c0084d4602a5adfc057055c5793a9af5de35283801fa2276dc0"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "hello-world-v#{version}-darwin-arm64" => "hello-world"
      else
        bin.install "hello-world-v#{version}-darwin-amd64" => "hello-world"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "hello-world-v#{version}-linux-arm64" => "hello-world"
      else
        bin.install "hello-world-v#{version}-linux-amd64" => "hello-world"
      end
    end
  end
end
