# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.9. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class HelloWorld < Formula
  desc ""
  homepage "https://github.com/muquit/hello-world"
  version "1.0.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/hello-world/releases/download/v1.0.2/hello-world-v1.0.2-darwin-arm64.d.tar.gz"
    sha256 "c3105931211e9b1ec297ca1af077a6395091f217cbdd4d804124fa25a977a7b6"
  end
  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/hello-world/releases/download/v1.0.2/hello-world-v1.0.2-darwin-amd64.d.tar.gz"
    sha256 "7713208087ddbe7d7587dd5a1d7ee50a902e0580f6056960488a03d06ce6e100"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/hello-world/releases/download/v1.0.2/hello-world-v1.0.2-linux-amd64.d.tar.gz"
    sha256 "3d22cbfd2c262234e8186a2980046f35fdd3ce097199ad8fd30a3663e2c4f8ef"
  end
  if OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/hello-world/releases/download/v1.0.2/hello-world-v1.0.2-linux-arm64.d.tar.gz"
    sha256 "a43c23b0c0a15deb365d2a45dbe428086d9cd83f0e80ebd4f8e7cc2783514d66"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "hello-world-v1.0.2-darwin-arm64" => "hello-world"
      else
        bin.install "hello-world-v1.0.2-darwin-amd64" => "hello-world"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "hello-world-v1.0.2-linux-arm64" => "hello-world"
      else
        bin.install "hello-world-v1.0.2-linux-amd64" => "hello-world"
      end
    end
  end
end
